export const CHAPTER_LIST_REQUEST = 'CHAPTER_LIST_REQUEST'
export const CHAPTER_LIST_SUCCESS = 'CHAPTER_LIST_SUCCESS'
export const CHAPTER_LIST_FAIL = 'CHAPTER_LIST_FAIL'

export const CHAPTER_DETAILS_REQUEST = 'CHAPTER_DETAILS_REQUEST'
export const CHAPTER_DETAILS_SUCCESS = 'CHAPTER_DETAILS_SUCCESS'
export const CHAPTER_DETAILS_FAIL = 'CHAPTER_DETAILS_FAIL'
export const CHAPTER_DETAILS_RESET = 'CHAPTER_DETAILS_RESET'

export const CHAPTER_DELETE_REQUEST = 'CHAPTER_DELETE_REQUEST'
export const CHAPTER_DELETE_SUCCESS = 'CHAPTER_DELETE_SUCCESS'
export const CHAPTER_DELETE_FAIL = 'CHAPTER_DELETE_FAIL'

export const CHAPTER_CREATE_REQUEST = 'CHAPTER_CREATE_REQUEST'
export const CHAPTER_CREATE_SUCCESS = 'CHAPTER_CREATE_SUCCESS'
export const CHAPTER_CREATE_FAIL = 'CHAPTER_CREATE_FAIL'
export const CHAPTER_CREATE_RESET = 'CHAPTER_CREATE_RESET'

export const CHAPTER_UPDATE_REQUEST = 'CHAPTER_UPDATE_REQUEST'
export const CHAPTER_UPDATE_SUCCESS = 'CHAPTER_UPDATE_SUCCESS'
export const CHAPTER_UPDATE_FAIL = 'CHAPTER_UPDATE_FAIL'
export const CHAPTER_UPDATE_RESET = 'CHAPTER_UPDATE_RESET'

export const CHAPTER_LIST_ALL_REQUEST = 'CHAPTER_LIST_ALL_REQUEST'
export const CHAPTER_LIST_ALL_SUCCESS = 'CHAPTER_LIST_ALL_SUCCESS'
export const CHAPTER_LIST_ALL_FAIL = 'CHAPTER_LIST_ALL_FAIL'